### ISSUE TITLE
UX: Error reporting

### ISSUE THREAD

**Issue by den-mentiei** [beardsvibe/buildfox#101]
We need much better diagnostics - error messages, etc.

As for now, exception callstacks are not interesting and messages are poor :(

**Comment by jimon** [comment]
Ok, so list of all exception places in a06ad6c821454786b9b5ab39f265824278c12158
- [x] buildfox.py:329 unknown argument
- [x] buildfox.py:386 unknown ide
- [x] lib_engine.py:143 two+ commands generate same target
- [x] lib_engine.py:181 unable to deduce auto
- [x] lib_engine.py:281 only = is supported in rule variables
- [x] lib_engine.py:316 unknown rule
- [x] lib_engine.py:345 cannot expand rule because len(inputs) != len(targets)
- [x] lib_environment.py:34 cannot find any compiler
- [x] lib_parser.py:29 unexpected indentation
- [x] lib_parser.py:279 was expecting identifier token
- [x] lib_parser.py:290 was expecting X token
- [x] lib_parser.py:298 was expecting any token
- [x] lib_parser.py:307 was expecting path token
- [x] lib_parser.py:317 was expecting EOL
- [x] lib_util.py:110 glob folder pattern should always end with /
- [x] lib_util.py:186 only use forward slashes in glob folder pattern
- [x] lib_version.py:19 required version has incorrect format
- [x] lib_version.py:24 buildfox is incompatible with required version
